baseURL = "https://www.eduardleroux.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Eddie"
theme = "cupper-hugo-theme"
enableGitInfo = false

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
description = "\t  Eddie's Blog "
homeMetaContent = "An accessibility-friendly Hugo theme, ported from the original Cupper project."
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/)."
dateFormat = "Jan 2, 2006"
codePenUser = "someUser"
katex = true
hideHeaderLinks = false
search = true
showThemeSwitcher = false
defaultDarkTheme = false
moveFooterToHeader = false
logoAlt = "An alternative text description of the logo"
customCss = [ "css/custom_01.css", "css/custom_02.css" ]
customJs = [ "js/custom_01.js", "js/custom_02.js" ]


[[menu.nav]]
name = "Home"
url = "/"
weight = 1

[[menu.nav]]
name = "About"
url = "/about/"
weight = 2

[[menu.nav]]
name = "Posts"
url = "/posts/"
weight = 3

#[[menu.nav]]
#name = "Paterns"
#url = "/patterns/"
#weight = 4

[[menu.nav]]
name = "Contact"
url = "/contact/"
weight = 5


[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

  [markup.highlight]
  codeFences = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4

  [markup.tableOfContents]
  endLevel = 6
  startLevel = 2
